"use client"

import { useState } from "react"
import { motion } from "framer-motion"
import { Plus, Minus, HelpCircle } from "lucide-react"

// FAQ data
const faqs = [
  {
    question: "What is docment.ai?",
    answer: "docment.ai is an AI-powered contract automation platform that helps you create, verify, and execute legally binding contracts within minutes. Our platform uses advanced AI to generate contracts that are compliant with Indian law, saving you time, money, and potential legal complications."
  },
  {
    question: "Are contracts generated by docment.ai legally binding?",
    answer: "Yes, all contracts generated through docment.ai are 100% legally binding and compliant with the Indian Contract Act, 1872 and Information Technology Act, 2000. Our platform ensures that all necessary legal elements are included, and our e-KYC verification provides an additional layer of security and legal validity."
  },
  {
    question: "How does the e-KYC process work?",
    answer: "Our e-KYC process uses government-approved identification methods to verify the identity of all parties involved in a contract. This typically involves submitting identity documents (such as Aadhaar), biometric verification, and/or video verification, depending on the level of security required for your specific transaction."
  },
  {
    question: "How long does it take to create a contract?",
    answer: "Most contracts can be created in under 2 minutes. Simply enter the transaction details, complete the e-KYC verification, and our AI system will generate a legally binding contract instantly. This is significantly faster than traditional methods which can take days or weeks."
  },
  {
    question: "What types of contracts can I create with docment.ai?",
    answer: "docment.ai supports a wide range of contracts including loan agreements, purchase agreements, rental agreements, service contracts, employment contracts, NDAs, and more. Our AI system can adapt to various transaction types to ensure comprehensive legal coverage."
  },
  {
    question: "How much does docment.ai cost?",
    answer: "We offer flexible pricing plans designed to suit different needs. Our basic plan starts with a pay-per-use model, while subscription plans are available for frequent users. Join our waitlist to receive detailed pricing information when we launch."
  }
]

export function FaqSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(null)

  const toggleFaq = (index: number) => {
    setOpenIndex(openIndex === index ? null : index)
  }

  return (
    <section id="faq" className="relative bg-background py-24 md:py-28">
      <div className="container relative z-10 mx-auto max-w-5xl px-4 md:px-6">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="text-center mb-16"
        >
          <div className="inline-block mb-3 px-4 py-1 bg-primary/10 text-primary rounded-full text-sm font-medium">
            Got Questions?
          </div>
          <h2 className="mb-6 text-3xl font-semibold tracking-tight sm:text-4xl md:text-5xl">
            Frequently Asked Questions
          </h2>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
            Everything you need to know about docment.ai and our contract automation platform
          </p>
        </motion.div>

        <div className="space-y-6">
          {faqs.map((faq, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.3, delay: index * 0.1 }}
              className="group"
            >
              <div 
                className={`border border-primary/10 rounded-xl overflow-hidden transition-all duration-300 ${
                  openIndex === index 
                    ? 'bg-gradient-to-br from-primary/5 to-background shadow-lg' 
                    : 'bg-background/80 hover:bg-muted/50'
                }`}
              >
                <button
                  onClick={() => toggleFaq(index)}
                  className="flex items-center justify-between w-full p-6 text-left"
                  aria-expanded={openIndex === index}
                >
                  <div className="flex items-center gap-4">
                    <div className={`rounded-full p-1.5 ${openIndex === index ? 'bg-primary/10 text-primary' : 'bg-muted/50 text-muted-foreground'}`}>
                      <HelpCircle className="h-5 w-5" />
                    </div>
                    <h3 className={`text-xl font-medium transition-colors duration-200 ${openIndex === index ? 'text-primary' : 'text-foreground'}`}>
                      {faq.question}
                    </h3>
                  </div>
                  <div className={`flex-shrink-0 size-8 rounded-full ${openIndex === index ? 'bg-primary text-white' : 'bg-muted/50 text-foreground'}`}>
                    <div className="flex items-center justify-center h-full">
                      {openIndex === index ? (
                        <Minus className="h-4 w-4" />
                      ) : (
                        <Plus className="h-4 w-4" />
                      )}
                    </div>
                  </div>
                </button>
                
                <motion.div
                  initial={false}
                  animate={{ 
                    height: openIndex === index ? 'auto' : 0,
                    opacity: openIndex === index ? 1 : 0
                  }}
                  transition={{ duration: 0.3 }}
                  className="overflow-hidden"
                >
                  <div className="p-6 pt-0 border-t border-primary/10">
                    <p className="text-muted-foreground leading-relaxed">
                      {faq.answer}
                    </p>
                  </div>
                </motion.div>
              </div>
            </motion.div>
          ))}
        </div>
        
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="mt-16 text-center"
        >
          <div className="p-8 rounded-xl bg-gradient-to-r from-primary/5 via-purple-500/5 to-blue-500/5 border border-primary/10">
            <h3 className="text-2xl font-bold mb-4">Still have questions?</h3>
            <p className="text-muted-foreground mb-6">
              If you couldn't find the answer to your question, feel free to reach out to our support team.
            </p>
            <a 
              href="#contact" 
              className="inline-flex items-center justify-center px-6 py-3 rounded-full bg-primary hover:bg-primary/90 text-white font-medium transition-colors duration-200"
              onClick={(e) => {
                e.preventDefault()
                document.getElementById('contact')?.scrollIntoView({ behavior: 'smooth' })
              }}
            >
              Contact Us
            </a>
          </div>
        </motion.div>
      </div>
    </section>
  )
}